# Generated by Django 4.1.2 on 2022-10-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_oilchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='aftermarket',
            field=models.ManyToManyField(to='main_app.aftermarket'),
        ),
    ]
